# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
# test

service: todo-api

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:ap-northeast-1:*:table/usersTable"


# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  user_create:
    handler: users/create.create
    events:
      - http:
          path: users
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path("$")
            statusCodes:
              200:
                pattern: ''
              400:
                pattern: '.*"statusCode": 400,.*'
                headers:
                  Content-Type: "'application/json'"
                template: $input.path("$.errorMessage")
  user_update:
    handler: users/update.update
    events:
      - http:
          path: users/{id}
          method: put
          integration: lambda
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path("$")
            statusCodes:
              200:
                pattern: ''
              400:
                pattern: '.*"statusCode": 400,.*'
                headers:
                  Content-Type: "'application/json'"
                template: $input.path("$.errorMessage")
  user_delete:
    handler: users/delete.delete
    events:
      - http:
          path: users/delete/{id}
          method: patch
          integration: lambda
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path("$")
            statusCodes:
              200:
                pattern: ''
              400:
                pattern: '.*"statusCode": 400,.*'
                headers:
                  Content-Type: "'application/json'"
                template: $input.path("$.errorMessage")

# DynamoDB settings
resources:
  Resources:
    # users
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: usersTable
    # tasks
    tasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: taskListId
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: taskListId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: tasksTable
    # task_lists
    taskListsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: deleteFlag
            AttributeType: B
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: deleteFlag
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: taskListsTable


